spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowCredentials: false
      routes:
        - id: authentication-microservice
          uri: lb://AUTHENTICATION
          predicates:
            - Path=/aeroaccess/auth/**
        - id: documents
          uri: lb://DOCUMENTS
          predicates:
            - Path=/aeroaccess/documents/**
          filters:
            - AuthFilter
        - id: users
          uri: lb://USERS
          predicates:
            - Path=/aeroaccess/users/**
          filters:
            - AuthFilter
  config:
    import: 'optional:configserver: instead.'

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    serviceUrl:
      defaultZone: 'http://eureka-service:8761/eureka/'

server:
  port: 8888

