apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
  labels:
    app: authentication
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  authentication
  template:
    metadata:
      labels:
        app:  authentication
    spec:
      containers:
        - name:  authentication
          image: authentication:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  selector:
    app: authentication
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: LoadBalancer
